language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mysql -e 'CREATE DATABASE mysql_test;'
  - mysql -e 'USE mysql_test;'
  - mysql -e 'CREATE TABLE test_page ( page_id int(16) NOT NULL auto_increment, page_template varchar(255), page_type varchar(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8;'
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text --verbose
